sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# Borrowed from https://github.com/travis-ci/travis-ci/issues/9815
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8
      dist: xenial
      sudo: true

script:
  - python -m doctest -v lru/__init__.py

